### ISSUE TITLE
Hoa main file (Core.php) must be included once.

### ISSUE THREAD

**Issue by Nisthar** [YnievesDotNet/FourStream#1]
I am getting "Hoa main file (Core.php) must be included once." when i try to run php artisan vendor:publish --provider="YnievesDotNet\FourStream\FourStreamServiceProvider"

**Comment by YnievesDotNet** [comment]
I'm searching this bug on my enviroment.

**Comment by Nisthar** [comment]
It would be nice if you can get the solution fast. because I removed this package and tried to install and run the two stream library by using the command php artisan vendor:publish --provider="CupOfTea\TwoStream\TwoStreamServiceProvider" --tag="config" and it also giving me the same Hoa main file (Core.php) must be included once.
There were no such error before that.

**Comment by YnievesDotNet** [comment]
you can show me your composer.json?

**Comment by Nisthar** [comment]
```
   {
     "name": "laravel/laravel",
      "description": "The Laravel Framework.",
      "keywords": ["framework", "laravel"],
      "license": "MIT",
"type": "project",
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*",
    "intervention/image": "^2.3",
    "ignited/laravel-omnipay": "^2.1",
    "cboden/ratchet": "^0.3.4",
    "cupoftea/twostream": "~1.0"
},
"require-dev": {
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~4.0",
    "phpspec/phpspec": "~2.1"
},
    "repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/CupOfTea696/Ratchet"
    }
],
"autoload": {
    "classmap": [
        "database"
    ],
    "psr-4": {
        "App\\": "app/"
    }
},
"autoload-dev": {
    "classmap": [
        "tests/TestCase.php"
    ]
},
"scripts": {
    "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "pre-update-cmd": [
        "php artisan clear-compiled"
    ],
    "post-update-cmd": [
        "php artisan optimize"
    ],
    "post-root-package-install": [
        "php -r \"copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
        "php artisan key:generate"
    ]
},
"config": {
    "preferred-install": "dist"
}

 }
```

**Comment by YnievesDotNet** [comment]
add in your composer.json this lines, and show me the results.

"hoa/cli": "~1.0"

thats apears as problem as Hoa Library.

I'm contact with the developer of this package for this error.

**Comment by YnievesDotNet** [comment]
FourStream dont require React.

This package use Hoa Websocket.

**Comment by Nisthar** [comment]
Ok. I'll try it.
Btw does this library support two way communication?

**Comment by YnievesDotNet** [comment]
yep, this package is twoways.

in this moment only message, has sended, the version 0.5, released soon, includes controllers parallels. for WAMPv2 requirements.

**Comment by Nisthar** [comment]
I tried. But Still the same error.

**Comment by Nisthar** [comment]
"Hoa main file (Core.php) must be included once." is displayed for every composer command.
Any way i can remove all the hoa packages installed?

**Comment by Nisthar** [comment]
Anything yet. My whole site is down with this error.

**Comment by YnievesDotNet** [comment]
the composer update run fine?

if not you have a corrupted installation, try comment in your composer.json all packages HOA and YnievesDotNet, then try 'composer dump-autoload'.

then show try install again ynievesdotnet/fourstream and show me your composer.lock

thanks

**Comment by Nisthar** [comment]
I managed to fix the issue by using a backup.

Btw does this library support push functionality?

**Comment by YnievesDotNet** [comment]
try again, I have create an issue in hoa project.

https://github.com/hoaproject/Core/issues/100

**Comment by YnievesDotNet** [comment]
I try now, on mi enviroment and run fine.
